project:
  title: "rzine-template"
  render: 
    - index.qmd


title: Classification et régionalisation
subtitle: "Application aux résultats des élections européennes de 2024 en France métropolitaine"
date: today
# date-modified: last-modified
author:
  - name: "Claude Grasland"
    affiliations:
      - name: "UMR 8504 Géographie-cités, Université Paris Cité "
        url: "https://geographie-cites.cnrs.fr/"
    orcid: 0000-0003-1504-4965


keywords: [classification, régionalisation, CAH, connexité]
abstract: |
     La combinaison des méthodes de classification et de régionalisation est facilitée par le développement d’une nouvelle fonction du package `adespatial` qui permet de regrouper les unités spatiales les plus ressemblantes en respectant la contrainte de connexité. Mise au point par des écologues canadiens, cette méthode de classification ascendante hiérarchique avec contrainte de voisinage est beaucoup plus simple d’emploi et efficace que les autres méthodes de régionalisation disponibles actuellement dans des packages tels que `rgeoda`. Elle s’appuie sur un corpus théorique d’analyse spatiale de la biodiversité des espaces animale ou végétale que l’on peut tenter de transposer à de nombreux problèmes géographiques, mais en adoptant une posture critique dans le cas de thématiques éloignées des questions de biologie végétale. Nous prenons ici comme exemple l’analyse du résultat des élections européennes de 2024 en France métropolitaine à trois niveaux d’agrégation : régions administratives, départements et circonscriptions législatives. Nous comparons à chaque échelle les résultats des méthodes de régionalisation et classification, et nous discutons leurs apports respectifs pour la compréhension des phénomènes de géographie électorale. 
draft: false # set to false once the build is running
published: true
doi: "10.48645/r6ng-wz66"

other-links:
  - text: Code source
    icon: github
    href: "https://github.com/rzine-reviews/rzine_regionalisation"

embed-resources: true
lang: fr-FR 
repo: "template"
toc-depth: 2

format:
  rzine-html: default
  rzine-pdf: default



